### ISSUE TITLE
Conflicts

### ISSUE THREAD

**Issue by Lupleg-dev** [cs60apa/Courses_UI#12]
You need to fix the conflicts by running the following commands
Step 1: Clone the repository or update your local repository with the latest changes.

git pull origin development
Step 2: Switch to the head branch of the pull request.

git checkout ui-optimization
Step 3: Merge the base branch into the head branch.

git merge development
Step 4: Fix the conflicts and commit the result.

See [Resolving a merge conflict using the command line](https://docs.github.com/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line) for step-by-step instructions on resolving merge conflicts.
Step 5: Push the changes.

git push -u origin ui-optimization

**Comment by marksikaundi** [comment]
Fixed the issue
